### PR TITLE
Generate data using GraphQL

### PR DESCRIPTION
**Pull request by cloudhoy**
### Changes
Updated `generate.ts` to use GitHub GraphQL API, which has the following advantages:
- keep requests within GitHub API rate limits 
- cut down on script execution time
- allows us to get filtered data directly from the response, reducing the need for data manipulation 
- typed response with `@octokit/graphql-schema` 😎

### Comments
If this PR is merged, #137 will need to be closed if it's still open.

### CODE REVIEW

**Comment by lucavallin** [comment]
Hey @cloudhoy! Super awesome, this is a major improvement. Thank you!
I am afraid I merged #137 before looking at this one, but I am happy to revert that later. I see there are a few conflicts in the meantime... If you can have a look at them, then we'll merge this ;)

**Comment by cloudhoy** [comment]
@lucavallin Not a problem! 👍
I've resolved the conflicts and there's no need to revert #137. Please take another look, thanks!

**Comment by lucavallin** [comment]
Looks great, thanks again!

**Review by lucavallin — APPROVED** [review]

**Comment by lucavallin** [comment]
Hey @cloudhoy! I merged the PR but in the pipeline an error seems to come up, my bad, I should have enabled Actions on PRs. Would you be able to open a new PR and have a look at https://github.com/lucavallin/first-issue/actions/runs/5793919555/job/15702527904? 🙏🏼

**Pull request merged**
