### PR TITLE
188 improve UI design of repository items

### PR DESCRIPTION
**Pull request by hasan75**
## General improvements for Issue [#188 ](https://github.com/lucavallin/first-issue/issues/188)
This PR consist of some UI design fixes that improve the repository design. The changes are:
- [x] Issue Numbers are aligned right
- [x] Added Color to RepositoryMetaData
- [x] Text Alignment refactored for the Repository Description
- [x] Removed text breaking css for the issue items.
- [x] Changed color for the issue number and IssueComment for the color contrast accessibility.
- [x] Applied Margin for issue title, where's no comment is present. This aligns the issue titles from right.

Here's the look after refactoring these things
image

### CODE REVIEW

**Comment by lucavallin** [comment]
@hasan75 Thanks! I would remove the colors, I am going to change them anyway later. If you do that, we can merge this!

**Comment by hasan75** [comment]
> @hasan75 Thanks! I would remove the colors, I am going to change them anyway later. If you do that, we can merge this!

@lucavallin I would love to do that. I do have a question though.
-  Which color should I remove? Color of Repository Metadata?

**Comment by lucavallin** [comment]
@hasan75 Sorry for the bad explanation. Yes, the repo metadata ;)

**Comment by nabarvn** [comment]
I'd like to suggest another way of ensuring that `IssueItem` maintains a consistent layout, regardless of whether there are comments associated with a specific issue. The proposed changes primarily target the `IssueCommentNum` and `IssueItem` components.

Changes to `IssueCommentNum`:

```diff
- <div className="mt-1 flex w-10 flex-row items-center justify-end text-secondary">
+ <div className="mt-1 flex min-w-[33px] flex-row items-center justify-end text-secondary">
+     {numIssues > 0 && (
+       <>
          <span className="mr-2 text-sm leading-snug">{numIssues}</span>
          <FontAwesomeIcon icon={faComment} />
+       </>
+     )}
  </div>
```

Changes to `IssueItem`:

```diff
- {issue.comments_count > 0 && <IssueCommentNum numIssues={issue.comments_count} />}
+ <IssueCommentNum numIssues={issue.comments_count} />
```

This is how it looks on my local machine after removing the `break-all` utility class from `IssueItem` anchor element:

Repository Card `IssueItem` Layout Fix

Your input would be greatly appreciated, @lucavallin!

**Comment by hasan75** [comment]
@nabarvn I have applied that by giving extra margin to issue title if there's no comment on that list! Your approach looks good also.

**Review by lucavallin — APPROVED** [review]
🥳 Awesome, thanks!

**Pull request merged**
