### PR TITLE
feature/sort repositories by stars

### PR DESCRIPTION
**Pull request by isaacwashere**
### Changes

- Extracts Context and Provider to their own separate file 
  - This was done (largely) because we are increasing the internal logic of the Context and keeping it in app.tsx would potentially clutter the file and make it harder to read
 - Place the key data points in the Context and rename it to express that
   - The thinking here was that, since (in the current version of the app) we are using the context as a form of "data warehouse" it made sense to name it AppData. 
 - Extract the hook meant to interface with the Context
   - Since the Context was extracted to its own file, and grew, it made sense to extract the Hook to its own file as well
   - Also, the Hook is the primary interface for Components to interact with the Context, and we'll be using the Hook as a traditional Hook 
  - Create the SortOrder logic within the context
  - Create the UI pieces (i.e. new sidebar button, and sidebar header)
  - Ensure the rest of the app is using the data from the hook

### CODE REVIEW

**Comment by lucavallin** [comment]
Excellent work, thanks a lot for the contribution! Do you think you have time to add sort by date too? Should be quite quick with the components you've added already 😄

**Comment by isaacwashere** [comment]
> Excellent work, thanks a lot for the contribution! Do you think you have time to add sort by date and number of new issues too? Should be quite quick with the components you've added already 😄 
> 
> 
> 
> That would close https://github.com/lucavallin/first-issue/issues/32 👓 

Thanks! And yea, sure thing! Just to clarify, what properties should be used for those sorting methods? Is a "sort by date" sorting based on the "last_modified" property? And is a sort by "number of new issues" sorting based on the length of issues?

**Comment by isaacwashere** [comment]
@lucavallin Hmm, okay so I think if we add both of those sorting methods, this PR could balloon a bit more than it already has. Right now this PR sets the foundation for sorting by adding the first 2 easy ones, that being stars (easy = the properties are directly on the Repo and there's no need to traverse another level deeper or modify the core Repository type). 

I agree that the 2 sorting methods you're referring to are valuable but they'll require more technical thought as to how to get the properties themselves. For example, we might need to modify the global Repository type for one, and the for the other we might need to sort repos by the number of issues that match some given criteria (which would be the basis for even more interesting features in the future, like sorting issues by a label, etc.). Each of these sorting types adds more complexity to this PR. And for the purposes of record-keeping and being able to read 1 unit of work at a time easily, it might be best to merge this and make 2 separate sorting Issues, with a few more details as to how we should do the sorting (which I'll probably take on 😅).

Of course, I'm open to giving it a shot here in this PR, in 1 go 🦾 (I'm always up for the challenge 😄 ) but I at least wanted to call out that it could make this PR a little bigger, and add just a tad more of a cognitive load to see everything that's happening. It's just a small risk, but I want to make sure we're aware of it.

As far as the looping for repos with the latest issues, we could (like you're saying) modify the generate.ts and add a `latest_issue_date` where we find the latest created_at date in the list of issues. And then we could sort repositories by that latest date, calling the Sort By button "Latest Issue(s)". That one seems like a simple change to get us closer to what we want. In terms of "sort repos by the number of issues matching the criteria", I'm not sure what is meant by criteria 🤔 I could use some clarification. 

Hahaaa, and thanks for the contribution credit 🙌 I'm really glad to be able to contribute to an OSS project that I believe in ❤️ I like what this project is doing, and I look forward to doing what I can to help it grow 👍

**Comment by lucavallin** [comment]
Thanks! Yes indeed, it is best to merge this one and then look at the other features in a separate branch. I will approve it and merge it so we can get it deployed 🥳 .

By `issues matching the criteria` I mean the issues that we pull in and store to the generated json, which already meet all criteria (they have the correct labels)

**Review by lucavallin — APPROVED** [review]
Great!

**Comment by isaacwashere** [comment]
noicee

I'll get started on the sort by latest issue created_at date. I think the solution you're suggesting is the simplest path. I'll put up a PR for it next 👍

**Pull request merged**
