### PR TITLE
Refactor react components

### LINKED ISSUE #20: Refactoring of React components
The components for the app can be split into smaller and more reusable ones. We would like to look into it and make changes where useful.

### PR DESCRIPTION
**Pull request by isaacwashere**
### Changes
- Breaks RepositoryItem into several smaller components 
- Adds IssueList, and IssueItem components
- Closes #20 

#### ℹ️ Repository information

**The repository has**:

- [ ] At least three issues with the `good first issue`, or other labels specified in `firstissue.json` (see `labels` and the end).
 - Link:
- [ ] At least 10 contributors.
- [ ] At least 1000 stars.
- [ ] Detailed setup instructions for the project.
 - Link:
- [ ] CONTRIBUTING.md
- [ ] Actively maintained (last updated less than 1 months ago).

### CODE REVIEW

**Comment by isaacwashere** [comment]
I recognize there are several areas where I could have taken this refactor even deeper, but I refrained from doing that because I think this refactoring process is something that should be done incrementally. So please, comment on any and everything you have thoughts on. Everything I've done is open for discussion. To get things started, here are some things that crossed my mind that you may (or may not) have thoughts/opinions on:
  - **Pass the entire Repository as a prop and simply Pick out of the necessary properties when “type”-ing the components props**: I opted not to do this because I didn’t really want to pass the entire object to the components, if they only needed certain things. Also, with the current way, you can see what’s getting used in a component without having to navigate to the component and view the props. However, I’m open to passing the entire repository and Pick-ing out of things if others (esp maintainers) want to do this
    - Example: `repository: Pick<Repository, "name" | "owner" | "url">;`
  - **Folder Structure**: I wanted to move some things into a RepositoryItem folder (specifically, `RepositoryItem`, `RepositoryItemTopBar`, `RepositoryLinkTitle`, `RepositoryDescription`, `RepositoryMetadata`, `RepositoryDescription`, and `RepositoryIssueNumberIndicator` would go in here)
  - **Naming of Components**: I’m not a big fan of the `RepositoryItemTopBar` so I wanted to crowd source 😅  some better names (if we deem this a component that should remain). The same goes for `RepositoryIssueNumberIndicator`. I considered `RepositoryTotalIssueNumberIndicator`, but that just gets even longer and I’d like to avoid that. 
  - **Really Small Components**: I may have broken this down a little too much, there are some small components, see `RepositoryDescription`. The thinking here was to make it so that (in the future), if there is a desire for a re-design, the components are small enough to be moved and modified individually. For example, if there is a need to add something just to the description, that option is cleanly available. And the same goes for RepositoryLinkTitle
  - **RepositoryLinkTitle**: I recognize that `RepositoryLinkTitle`, and the link inside the `IssueItem` component are very similar. I considered separating them out into another component, but opted not to because it really is just a standard link for the issue. Whereas the `RepositoryLinkTtitle` is of a greater importance. This (along with just about everything mentioned) is a question of preference, so I’m open to separating them. I just figured that might be a bit much
  - **isIssueOpen**: I sort of like `hasOpenIssue` a little more. I wanted to change it but opted not to because it was just a mild preference and figured it’s not a problem to leave it as is. But I wanted to mention it.

**Comment by lucavallin** [comment]
@isaacwashere Thanks for your contribution! I am just back from my holidays - I will have a look at the PR soon. 🙏🏼  again for the refactoring!

**Comment by lucavallin** [comment]
Awesome refactoring, thanks! I will merge these changes and then we can look at how our feelings evolve wrt the current structure.

**Comment by isaacwashere** [comment]
@lucavallin I hope you enjoyed the holiday 😊 Thanks for the feedback! I'm glad I was able to help! 💪 

Yes, please play around with this new structure and make as many issues as you can think of that further address the refactoring needs. And provided the issues aren't too complex, 😅 I'd be happy to work on (some of) them. 

The original issue wasn't very strict in expressing what was desired, so I went with the "minimum amount to suffice". But there are definitely ways this could have gone much deeper and more intense (some ways I listed, some I didn't). Regardless, I'm glad this was a benefit to the repo. I like what this project is doing, and I look forward to contributing more in the future 😊

**Pull request merged**
