### PR TITLE
Update action node version to 18

### LINKED ISSUE #149: Pipeline build error
An error occurred during the build process after merging PR #139:

image

> Hey @cloudhoy! I merged the PR but in the pipeline an error seems to come up, my bad, I should have enabled Actions on PRs. Would you be able to open a new PR and have a look at https://github.com/lucavallin/first-issue/actions/runs/5793919555/job/15702527904? 🙏🏼  

_Originally posted by @lucavallin in https://github.com/lucavallin/first-issue/issues/139#issuecomment-1669046414_

### PR DESCRIPTION
**Pull request by cloudhoy**
Closes #149

Updates node versions for GitHub actions from `16` to `18`, and reverts the revert for #139.

### CODE REVIEW

**Comment by cloudhoy** [comment]
👋 Hey @lucavallin! Looks like Actions are failing with a `401` error when making requests to the GitHub API.

Perhaps the `GH_PERSONAL_ACCESS_TOKEN` token has expired?

**Comment by lucavallin** [comment]
Hey @cloudhoy! The token is not expired, I think it has to do with the author of the PR? I am not sure, I will merge this and see how it goes. Thanks for the fixes!

**Review by lucavallin — APPROVED** [review]

**Comment by cloudhoy** [comment]
@lucavallin Great, thanks! 😄

I did some reading and it looks like [fork-origin PRs do not have access to secrets](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks) for security reasons:

> In order to protect public repositories for malicious users we run all pull request workflows raised from repository forks with a read-only token and no access to secrets.

Anyways, here's the [passing job](https://github.com/cloudhoy/first-issue-tcheong/actions/runs/5811512353/job/15755657069) from my fork for your reference.

**Comment by lucavallin** [comment]
Hey @cloudhoy! No token errors in the workflow, however, we are being rate-limited, see https://github.com/lucavallin/first-issue/actions/runs/5815296740/job/15766591898#step:7:27. How would you address this?

**Comment by cloudhoy** [comment]
👋 @lucavallin I think allowing retries upon hitting secondary rate limits should help. 

This is probably also a sign to increase the time between requests. Though I'm thinking about making the requests serially (in line with [recommended best practices](https://docs.github.com/en/rest/guides/best-practices-for-integrators?apiVersion=2022-11-28#dealing-with-secondary-rate-limits)) instead of concurrently as we're doing right now. 

What do you think?

**Comment by lucavallin** [comment]
That's a great idea, thanks for looking into this!

**Pull request merged**
