### PR TITLE
Automatic update of the repository list

### PR DESCRIPTION
**Pull request by alphavector**
Thanks to the work of @alexey-milovidov, we have a structured list of all github events
Read more at https://ghe.clickhouse.tech/

We can go to the database and get a list of repositories at once, specifying the necessary filters of labels, number of participants and number of stars

Some explanation of what's going on

`uniqIf(creator_user_login, event_type = 'PullRequestEvent' and merged = 1) AS contributors`

This is a rough calculation of the number of contributors in the repository -- the number of unique authors who have merged PRs. 
The number is not exact, but it's close to the truth. 
We cannot get an exact number because the database does not hold information about commits

In general, what happens is as follows:
1) Get a list of popular and current repositories
2) Filter by label and by number of problems
3) Then use jq to update the repository list. A new list is added to the existing list so that you can add additional repositories manually

### CODE REVIEW

**Comment by lucavallin** [comment]
Hi @alphavector, thanks for your contribution! A few questions:

- How are `firstissue_repositories.sql` and `update_repositories.sh` used, and what for?
- `firstissue.json` now contains ~3000 repositories. I believe the API will block us (we often hit the limit already) - how can we tackle this?

**Comment by alphavector** [comment]
`update_repositories.sh` is used to update the list of repositories in the file `firstissue.json`

`firstissue_repositories.sql` is an sql query that can be used to get the list of repositories
The `github_events` table stores all the events (there are almost `5.5 billion` of them now) and the database itself is located at https://play.clickhouse.com/play?user=play. The data in the table is synchronized every 10 minutes

In `update_repositories.sh` we send a sql-query `firstissue_repositories.sql` to https://play.clickhouse.com and in return we get the list of repositories we need
Then we merge this list with the list from file firstissue.json



Regarding the query limit - we can do things a bit smarter

All information about problems and tags is in the table github_events, we can get this information from the database instead of going to API
But we can't refuse from API queries completely - table `github_events` doesn't contain information about languages.

I propose the following algorithm:

Step 1 - definition of the repository list

1) Obtain a list of repositories from the table `github_events`, which meet the criteria set
2) Put this list into `firstissue.json`
3) Manually add to the list if you want

Step 2 - fetching

1) Run a query in the `github_events` table to retrieve:
```
- stars
- last activity

- issue id
- issue title
- issue body
- number of comments
```
2) Define a file (let's say `repo_info.json`) that will store a short description and list of languages for each repository.
3) Query github API to get repository description and languages. With the `repo_info.json` file in place, we can avoid sending 3000 queries over and over again and only do it for new repositories. But the first time we will have to make 3,000 queries.
4) Merge the results of the first and third points, put them into `generated.ts`


This way we can reduce number of requests to API

**Comment by lucavallin** [comment]
Hi @alphavector, thanks for the explanation. I have some follow-up thoughts:
1. Who's maintaining the data in clickhouse?
2. I like the solution you proposed for limiting the number of calls we make to the GitHub API, however, we make at least two calls for each repo, one for the general information (including stars, title, description... not something we can cache I believe) and one for fetching issues for each label (definitely something we can't cache). A solution would be to have a backend of some kind fetching information from GitHub at a much slower speed (let's say throughout the day), but then `firstissue.dev` should become a "regular" web app rather than just a static page loading data from some pre-generated json.

**Comment by alphavector** [comment]
1) In clickhouse chat I clarified, the data is maintained by Alexey Milovidov, Clickhouse CTO (if anything I have nothing to do with clickhouse team). But there is no guarantee of 100% availability and relevance in the future, as I understood.


2) Requests for problem list, stars we get from `clickhouse`, these calls are "free", unlike `github`. And this is exactly the kind of information that changes frequently. We can at least make a request every second.

And we get the description and language list from the api `github`. This is rarely changing data, which we can ask for not so often, within the established limits. And we can cache this data.

I.e. we essentially make 1 "paid" request, the requests in `clickhouse` are not limited in any way


By the way, the source does not have to be clickhouse, `Google BigQuery` has the same public data set `githubarchive`. It is updated once a day, but who maintains the data - unknown
`BigQuery` also has a data set `bigquery-public-data.github_repos.languages` with a list of languages for each repository, but I did not find there such popular repositories as `python/cpython` and `rust-lang/rust`

So I suggest request languages and descriptions from the api, and everything else from the database

**Comment by lucavallin** [comment]
Sounds good to me, thanks for checking! Would it be possible to replace the bash script and make that call part of `generate.ts` ? That way, we only need to run one scripts. Thanks!

**Comment by lucavallin** [comment]
Closing because of lack of updates. Feel free to re-open when updated.

**Pull request closed without merging**
